language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
script:
  - ./gradlew assembleDebug

before_deploy:
  - mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/test.apk

deploy:              # 部署
  provider: releases # 部署到GitHub Release，除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  api_key:           # 填写GitHub的token （Settings -> Personal access tokens -> Generate new token）
    secure: "${GITHU_AUTH}"
  file: app/build/outputs/apk/debug/test.apk   # 部署文件路径
  skip_cleanup: true     # 设置为true以跳过清理,不然apk文件就会被清理
  on:     # 发布时机
    tags: true       # tags设置为true表示只有在有tag的情况下才部署